/* Ancestry Atlas v3.7.0 — completed-biography film and native AirPlay adapter. */
(()=>{
  'use strict';
  const $=id=>document.getElementById(id),modal=$('tvFilmModal'),video=$('tvFilmVideo'),complete=$('tvFilmComplete');let lastFocus=null;
  function open(){lastFocus=document.activeElement;$('lineChooser')?.classList.remove('open');$('lineChooser')?.setAttribute('aria-hidden','true');$('landing')?.classList.add('hidden');modal?.classList.add('open');modal?.setAttribute('aria-hidden','false');complete?.classList.remove('open');video?.load();$('filmChooseTV')?.focus({preventScroll:true})}
  function close({showTree=false}={}){try{video?.pause()}catch(e){}modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true');complete?.classList.remove('open');if(showTree){try{selected='james_sheldon';cinematicFocus('james_sheldon','family');draw()}catch(e){}return}const chooser=$('lineChooser');chooser?.classList.add('open');chooser?.setAttribute('aria-hidden','false');if($('tourBranchChoice'))$('tourBranchChoice').hidden=true;if($('tourViewingChoice'))$('tourViewingChoice').hidden=false;($('tourWatchTV')||$('tourWatchHere')||lastFocus)?.focus?.({preventScroll:true})}
  function chooseTelevision(){if(typeof video?.webkitShowPlaybackTargetPicker==='function'){video.webkitShowPlaybackTargetPicker();video.play().catch(()=>{});return}$('filmConnectionHelp').textContent='Use the AirPlay control in the video player, or choose Play Full Screen for an HDMI-connected display.';video?.play().catch(()=>{})}
  async function fullscreen(){try{if(typeof video?.webkitEnterFullscreen==='function'){video.webkitEnterFullscreen();video.play().catch(()=>{});return}if(video?.requestFullscreen)await video.requestFullscreen();await video?.play()}catch(e){video?.play().catch(()=>{})}}
  function replay(){complete?.classList.remove('open');video.currentTime=0;video.play().catch(()=>{})}
  $('filmChooseTV')?.addEventListener('click',chooseTelevision);$('filmFullscreen')?.addEventListener('click',fullscreen);$('filmClose')?.addEventListener('click',()=>close());document.querySelectorAll('[data-film-return-tree]').forEach(button=>button.addEventListener('click',()=>close({showTree:true})));$('filmReplay')?.addEventListener('click',replay);video?.addEventListener('ended',()=>{complete?.classList.add('open');$('filmReplay')?.focus()});modal?.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();close()}});window.AncestryTVFilm={open,close};
})();
